/* $api.ts was generated by aspida@1.6.3 */
/* eslint-disable */
// prettier-ignore
import type { Methods as Methods0 } from './entries.json'
// prettier-ignore
import type { Methods as Methods1 } from './test-4'
// prettier-ignore
import type { Methods as Methods2 } from './test-4/[fugaId]'
// prettier-ignore
import type { Methods as Methods3 } from './test-4/fuga aa'

// prettier-ignore
type BasicHeaders = Record<string, string>

// prettier-ignore
type Params = {
  query?: any
  headers?: any
  body?: any
  init?: RequestInit
}

// prettier-ignore
const headersToObject = (headers: Headers): any =>
  [...headers.entries()].reduce((prev, [key, val]) => ({ ...prev, [key]: val }), {})

// prettier-ignore
const dataToURLString = (data: Record<string, any>) => {
  const searchParams = new URLSearchParams()

  Object.entries(data).forEach(([key, val]) => {
    if (Array.isArray(val)) {
      val.forEach(v => searchParams.append(key, v))
    } else if (val != null) {
      searchParams.append(key, val)
    }
  })

  return searchParams.toString()
}

// prettier-ignore
const optionToRequest = (method: string, params?: Params): RequestInit => {
  if (!params?.body) return { method, ...params?.init }

  return {
    method,
    body: JSON.stringify(params.body),
    ...params.init,
    headers: { 'Content-Type': 'application/json;charset=utf-8', ...params.init?.headers, ...params.headers }
  }
}

// prettier-ignore
type ServerData = { status?: number; headers?: BasicHeaders; body?: any }
// prettier-ignore
type ResType = 'json' | 'text' | 'arrayBuffer' | 'blob' | 'formData' | 'void'

// prettier-ignore
const client: typeof fetch = typeof fetch !== 'undefined' ? fetch : require('node-fetch')
// prettier-ignore
const send = async <
  Success extends ServerData = { status: number; headers: BasicHeaders },
  Failure extends ServerData = { status: number; headers: BasicHeaders }
>(
  method: string,
  baseURL: string,
  url: string,
  resType: ResType,
  errType: ResType,
  params?: Params
): Promise<
  | { res: Success; err?: undefined }
  | { res?: undefined; err: { type: 'httpError'; data: Failure } }
  | { res?: undefined; err: { type: 'networkError'; data: TypeError } }
> => {
  try {
    const res = await client(
      `${baseURL}${url}${params?.query ? `?${dataToURLString(params.query)}` : ''}`,
      optionToRequest(method, params)
    )

    if (res.ok) {
      return {
        res: {
          status: res.status,
          headers: headersToObject(res.headers),
          body: resType === 'void' ? undefined : await res[resType]()
        } as Success
      }
    } else {
      return {
        err: {
          type: 'httpError',
          data: {
            status: res.status,
            headers: headersToObject(res.headers),
            body: errType === 'void' ? undefined : await res[errType]()
          } as Failure
        }
      }
    }
  } catch (e) {
    return { err: { type: 'networkError', data: e } }
  }
}

// prettier-ignore
const BASE_URL = ''
// prettier-ignore
const PATH0 = '/v1.1/2/[hogeId@string]/entries.json/'
// prettier-ignore
const PATH1 = '/v1.1/2/[hogeId@string]/test-4/'
// prettier-ignore
const PATH2 = '/'
// prettier-ignore
const PATH3 = '/v1.1/2/[hogeId@string]/test-4/fuga aa/'
// prettier-ignore
const GET = 'GET'
// prettier-ignore
const POST = 'POST'
// prettier-ignore
const PUT = 'PUT'
// prettier-ignore
const DELETE = 'DELETE'

// prettier-ignore
export const createApi = (config?: { baseURL?: string; trailingSlash?: boolean; init?: RequestInit }) => {
  const prefix = (config?.baseURL ?? BASE_URL).replace(/\/$/, '')

  return {
    entries_json: {
      $get: (option?: { init?: RequestInit }) =>
        send<Methods0['get']['res']>(GET, prefix, PATH0, 'json', 'void', option),
      $path: () => `${prefix}${PATH0}`
    },
    test_4: {
      /**
       * _fugaId comment
       */
      _fugaId: (val1: number | string) => {
        const prefix1 = `${PATH1}${val1}`

        return {
          $get: (option?: Methods2['get']['req'] & { init?: RequestInit }) =>
            send<Methods2['get']['res']>(GET, prefix, `${prefix1}${PATH2}`, 'json', 'void', option),
          $post: (option: Methods2['post']['req'] & { init?: RequestInit }) =>
            send<Methods2['post']['res']>(POST, prefix, `${prefix1}${PATH2}`, 'json', 'void', option),
          $put: (option: Methods2['put']['req'] & { init?: RequestInit }) =>
            send<Methods2['put']['res']>(PUT, prefix, `${prefix1}${PATH2}`, 'json', 'void', option),
          /**
           * _fugaId delete method
           * @returns _fugaId resBody
           */
          $delete: (option: Methods2['delete']['req'] & { init?: RequestInit }) =>
            send<Methods2['delete']['res']>(DELETE, prefix, `${prefix1}${PATH2}`, 'json', 'void', option),
          $path: (option?: { method?: 'get'; query: Methods2['get']['req']['query'] } | { method: 'post'; query: Methods2['post']['req']['query'] } | { method: 'put'; query: Methods2['put']['req']['query'] } | { method: 'delete'; query: Methods2['delete']['req']['query'] }) =>
            `${prefix}${prefix1}${PATH2}${option?.query ? `?${dataToURLString(option.query)}` : ''}`
        }
      },
      fuga_aa: {
        $get: (option: Methods3['get']['req'] & { init?: RequestInit }) =>
          send<Methods3['get']['res']>(GET, prefix, PATH3, 'json', 'void', option),
        $post: (option: Methods3['post']['req'] & { init?: RequestInit }) =>
          send<Methods3['post']['res']>(POST, prefix, PATH3, 'json', 'void', option),
        $put: (option: Methods3['put']['req'] & { init?: RequestInit }) =>
          send<Methods3['put']['res']>(PUT, prefix, PATH3, 'json', 'void', option),
        $delete: (option: Methods3['delete']['req'] & { init?: RequestInit }) =>
          send<Methods3['delete']['res']>(DELETE, prefix, PATH3, 'json', 'void', option),
        $path: (option?: { method?: 'get'; query: Methods3['get']['req']['query'] } | { method: 'post'; query: Methods3['post']['req']['query'] } | { method: 'put'; query: Methods3['put']['req']['query'] } | { method: 'delete'; query: Methods3['delete']['req']['query'] }) =>
          `${prefix}${PATH3}${option?.query ? `?${dataToURLString(option.query)}` : ''}`
      },
      $get: (option: Methods1['get']['req'] & { init?: RequestInit }) =>
        send<{}>(GET, prefix, PATH1, 'void', 'void', option),
      $post: (option?: Methods1['post']['req'] & { init?: RequestInit }) =>
        send<{}>(POST, prefix, PATH1, 'void', 'void', option),
      $put: (option?: Methods1['put']['req'] & { init?: RequestInit }) =>
        send<Methods1['put']['res']>(PUT, prefix, PATH1, 'json', 'void', option),
      $delete: (option: Methods1['delete']['req'] & { init?: RequestInit }) =>
        send<Methods1['delete']['res']>(DELETE, prefix, PATH1, 'json', 'void', option),
      $path: (option?: { method?: 'get'; query: Methods1['get']['req']['query'] } | { method: 'post'; query: Methods1['post']['req']['query'] } | { method: 'put'; query: Methods1['put']['req']['query'] } | { method: 'delete'; query: Methods1['delete']['req']['query'] }) =>
        `${prefix}${PATH1}${option?.query ? `?${dataToURLString(option.query)}` : ''}`
    }
  } as const
}
