/* $api.ts was generated by aspida@1.6.3 */
/* eslint-disable */
// prettier-ignore
import type { Methods as Methods0 } from '.'
// prettier-ignore
import type { Methods as Methods1 } from './2/[hogeId@number]'
// prettier-ignore
import type { Methods as Methods2 } from './2/[hogeId@string]/entries.json'
// prettier-ignore
import type { Methods as Methods3 } from './2/[hogeId@string]/test-4'
// prettier-ignore
import type { Methods as Methods4 } from './2/[hogeId@string]/test-4/[fugaId]'
// prettier-ignore
import type { Methods as Methods5 } from './2/[hogeId@string]/test-4/fuga aa'
// prettier-ignore
import type { Methods as Methods6 } from './2/[hogeId]'
// prettier-ignore
import type { Methods as Methods7 } from './3.1'
// prettier-ignore
import type { Methods as Methods8 } from './[articleId].json'
// prettier-ignore
import type { Methods as Methods9 } from './users/[userId@string]'

// prettier-ignore
type BasicHeaders = Record<string, string>

// prettier-ignore
type Params = {
  query?: any
  headers?: any
  body?: any
  init?: RequestInit
}

// prettier-ignore
const headersToObject = (headers: Headers): any =>
  [...headers.entries()].reduce((prev, [key, val]) => ({ ...prev, [key]: val }), {})

// prettier-ignore
const appendDataToFormData = (data: Record<string, any>, formData: FormData) => {
  Object.entries(data).forEach(([key, val]) => {
    if (Array.isArray(val)) {
      val.forEach(v => formData.append(key, v))
    } else if (val != null) {
      formData.append(key, val)
    }
  })

  return formData
}

// prettier-ignore
const dataToURLString = (data: Record<string, any>) => {
  const searchParams = new URLSearchParams()

  Object.entries(data).forEach(([key, val]) => {
    if (Array.isArray(val)) {
      val.forEach(v => searchParams.append(key, v))
    } else if (val != null) {
      searchParams.append(key, val)
    }
  })

  return searchParams.toString()
}

// prettier-ignore
const optionToRequest = (
  method: string,
  params?: Params,
  format?: BodyInit
): RequestInit => {
  if (!params) return { method }

  let body
  let headers: BasicHeaders = {}

  switch (format) {
    case undefined:
      break;
    case 'FormData':
      if (typeof FormData !== 'undefined') {
        body = appendDataToFormData(params.body, new FormData())
      } else {
        const formData = new (require('form-data'))()
        body = appendDataToFormData(params.body, formData)
        headers = formData.getHeaders()
      }
      break
    case 'URLSearchParams':
      body = dataToURLString(params.body)
      headers['Content-Type'] = 'application/x-www-form-urlencoded;charset=utf-8'
      break
    case 'ArrayBuffer':
    case 'string':
    case 'Blob':
      body = params.body
      break
    default:
      body = JSON.stringify(params.body)
      headers['Content-Type'] = 'application/json;charset=utf-8'
      break
  }

  return { ...params.init, method, body, headers: { ...headers, ...params.init?.headers, ...params.headers } }
}

// prettier-ignore
type ServerData = { status?: number; headers?: BasicHeaders; body?: any }

// prettier-ignore
type NormalizedResponse<Success extends ServerData, Failure extends ServerData> =
  | { isSuccess: true; stream: Response['body']; data: Success }
  | { isSuccess: false; isFailure: true; stream: Response['body']; data: Failure }
  | { isSuccess: false; isFailure: false; err: Error };

// prettier-ignore
const send = async <Success extends ServerData = { status: number; headers: BasicHeaders }, Failure extends ServerData = { status: number; headers: BasicHeaders }>(
  client: typeof fetch,
  method: string,
  baseURL: string,
  url: string,
  resType: 'json' | 'text' | 'arrayBuffer' | 'blob' | 'formData' | 'void',
  params?: Params,
  format?: BodyInit
): Promise<NormalizedResponse<Success, Failure>> => {
  try {
    const res = await client(
      `${baseURL}${url}${
        params?.query ? `?${dataToURLString(params.query)}` : ''
      }`,
      optionToRequest(method, params, format)
    )

    if (res.ok) {
      return {
        isSuccess: true,
        stream: res.body,
        data: {
          status: res.status,
          headers: headersToObject(res.headers),
          body: resType === 'void' ? undefined : await res[resType](),
        } as Success
      };
    } else {
      return {
        isSuccess: false,
        isFailure: true,
        stream: res.body,
        data: {
          status: res.status,
          headers: headersToObject(res.headers),
        } as Failure
      };
    }
  } catch (err) {
    return {
      isSuccess: false,
      isFailure: false,
      err,
    };
  }
}

// prettier-ignore
export const createApi = (config?: { baseURL?: string; trailingSlash?: boolean; init?: RequestInit}) => {
  const f = typeof fetch !== 'undefined' ? fetch : require('node-fetch')
  const prefix = (config?.baseURL ?? '').replace(/\/$/, '')
  const PATH0 = '/v1.1/'
  const PATH1 = '/v1.1/2/'
  const PATH2 = '/'
  const PATH3 = '/entries.json/'
  const PATH4 = '/test-4/'
  const PATH5 = '/test-4/fuga aa/'
  const PATH6 = '/v1.1/3.1/'
  const PATH7 = '/v1.1/users/'
  const GET = 'GET'
  const POST = 'POST'
  const PUT = 'PUT'
  const DELETE = 'DELETE'

  return {
    $2: {
      hogeId_number: (val1: number) => {
        const prefix1 = `${PATH1}${val1}`

        return {
          $get: (option: Methods1['get']['req'] & { init?: RequestInit }) =>
            send<Methods1['get']['res']>(f, GET, prefix, `${prefix1}${PATH2}`, 'json', option),
          $path: (option?: { method?: 'get'; query: Methods1['get']['req']['query'] }) =>
            `${prefix}${prefix1}${PATH2}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
        }
      },
      hogeId_string: (val1: string) => {
        const prefix1 = `${PATH1}${val1}`

        return {
          entries_json: {
            $get: (option?: { init?: RequestInit }) =>
              send<Methods2['get']['res']>(f, GET, prefix, `${prefix1}${PATH3}`, 'json', option),
            $path: () => `${prefix}${prefix1}${PATH3}`
          },
          test_4: {
            /**
             * _fugaId comment
             */
            fugaId: (val3: number | string) => {
              const prefix3 = `${prefix1}${PATH4}${val3}`

              return {
                $get: (option?: Methods4['get']['req'] & { init?: RequestInit }) =>
                  send<Methods4['get']['res']>(f, GET, prefix, `${prefix3}${PATH2}`, 'json', option),
                $post: (option: Methods4['post']['req'] & { init?: RequestInit }) =>
                  send<Methods4['post']['res']>(f, POST, prefix, `${prefix3}${PATH2}`, 'json', option),
                $put: (option: Methods4['put']['req'] & { init?: RequestInit }) =>
                  send<Methods4['put']['res']>(f, PUT, prefix, `${prefix3}${PATH2}`, 'json', option),
                /**
                 * _fugaId delete method
                 * @returns _fugaId resBody
                 */
                $delete: (option: Methods4['delete']['req'] & { init?: RequestInit }) =>
                  send<Methods4['delete']['res']>(f, DELETE, prefix, `${prefix3}${PATH2}`, 'json', option),
                $path: (option?: { method?: 'get'; query: Methods4['get']['req']['query'] } | { method: 'post'; query: Methods4['post']['req']['query'] } | { method: 'put'; query: Methods4['put']['req']['query'] } | { method: 'delete'; query: Methods4['delete']['req']['query'] }) =>
                  `${prefix}${prefix3}${PATH2}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
              }
            },
            fuga_aa: {
              $get: (option: Methods5['get']['req'] & { init?: RequestInit }) =>
                send<Methods5['get']['res']>(f, GET, prefix, `${prefix1}${PATH5}`, 'json', option),
              $post: (option: Methods5['post']['req'] & { init?: RequestInit }) =>
                send<Methods5['post']['res']>(f, POST, prefix, `${prefix1}${PATH5}`, 'json', option),
              $put: (option: Methods5['put']['req'] & { init?: RequestInit }) =>
                send<Methods5['put']['res']>(f, PUT, prefix, `${prefix1}${PATH5}`, 'json', option),
              $delete: (option: Methods5['delete']['req'] & { init?: RequestInit }) =>
                send<Methods5['delete']['res']>(f, DELETE, prefix, `${prefix1}${PATH5}`, 'json', option),
              $path: (option?: { method?: 'get'; query: Methods5['get']['req']['query'] } | { method: 'post'; query: Methods5['post']['req']['query'] } | { method: 'put'; query: Methods5['put']['req']['query'] } | { method: 'delete'; query: Methods5['delete']['req']['query'] }) =>
                `${prefix}${prefix1}${PATH5}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
            },
            $get: (option: Methods3['get']['req'] & { init?: RequestInit }) =>
              send<{}>(f, GET, prefix, `${prefix1}${PATH4}`, 'void', option),
            $post: (option?: Methods3['post']['req'] & { init?: RequestInit }) =>
              send<{}>(f, POST, prefix, `${prefix1}${PATH4}`, 'void', option),
            $put: (option?: Methods3['put']['req'] & { init?: RequestInit }) =>
              send<Methods3['put']['res']>(f, PUT, prefix, `${prefix1}${PATH4}`, 'json', option),
            $delete: (option: Methods3['delete']['req'] & { init?: RequestInit }) =>
              send<Methods3['delete']['res']>(f, DELETE, prefix, `${prefix1}${PATH4}`, 'json', option),
            $path: (option?: { method?: 'get'; query: Methods3['get']['req']['query'] } | { method: 'post'; query: Methods3['post']['req']['query'] } | { method: 'put'; query: Methods3['put']['req']['query'] } | { method: 'delete'; query: Methods3['delete']['req']['query'] }) =>
              `${prefix}${prefix1}${PATH4}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
          }
        }
      },
      hogeId: (val1: number | string) => {
        const prefix1 = `${PATH1}${val1}`

        return {
          $get: (option?: { init?: RequestInit }) =>
            send<Methods6['get']['res']>(f, GET, prefix, `${prefix1}${PATH2}`, 'json', option),
          $path: () => `${prefix}${prefix1}${PATH2}`
        }
      }
    },
    /**
     * 3.1 comment
     */
    $3_1: {
      /**
       * 3.1 get method comment
       * @param option.headers - 3.1 reqHeaders
       */
      $get: (option?: Methods7['get']['req'] & { init?: RequestInit }) =>
        send<Methods7['get']['res']>(f, GET, prefix, PATH6, 'json', option),
      $post: (option: Omit<Methods7['post']['req'], 'format'> & { init?: RequestInit }) =>
        send<Methods7['post']['res']>(f, POST, prefix, PATH6, 'json', option, 'URLSearchParams'),
      $path: (option?: { method?: 'get'; query: Methods7['get']['req']['query'] } | { method: 'post'; query: Methods7['post']['req']['query'] }) =>
        `${prefix}${PATH6}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
    },
    articleId_json: (val0: number | string) => {
      const prefix0 = `${PATH0}${val0}.json`

      return {
        $get: (option?: { init?: RequestInit }) =>
          send<Methods8['get']['res']>(f, GET, prefix, `${prefix0}${PATH2}`, 'json', option),
        $path: () => `${prefix}${prefix0}${PATH2}`
      }
    },
    users: {
      userId: (val1: string) => {
        const prefix1 = `${PATH7}${val1}`

        return {
          $get: (option: Methods9['get']['req'] & { init?: RequestInit }) =>
            send<Methods9['get']['res']>(f, GET, prefix, `${prefix1}${PATH2}`, 'json', option),
          $post: (option: Methods9['post']['req'] & { init?: RequestInit }) =>
            send<Methods9['post']['res']>(f, POST, prefix, `${prefix1}${PATH2}`, 'json', option),
          $path: (option?: { method?: 'get'; query: Methods9['get']['req']['query'] } | { method: 'post'; query: Methods9['post']['req']['query'] }) =>
            `${prefix}${prefix1}${PATH2}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
        }
      }
    },
    $get: (option?: Methods0['get']['req'] & { init?: RequestInit }) =>
      send<Methods0['get']['res']>(f, GET, prefix, PATH0, 'json', option),
    $path: (option?: { method?: 'get'; query: Methods0['get']['req']['query'] }) =>
      `${prefix}${PATH0}${option && option.query ? `?${dataToURLString(option.query)}` : ''}`
  }
}
