

name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
    paths:
      - 'packages/aspida/**'
      - '.github/workflows/release-aspida.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/aspida
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@simula-labs'
      - run: npm install
      - run: npm run build
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
